Add 'c4 disk_usage'

diff --git a/cbc/shared/bin/c4 b/cbc/shared/bin/c4
--- a/cbc/shared/bin/c4
+++ b/cbc/shared/bin/c4
@@ -11,6 +11,7 @@
 ###  c4 nodes       - List nodes that are up
 ###  c4 nodes       - List all users
 ###  c4 head        - List users' usage of headnode
+###  c4 disk_usage  - Summarize a users disk usage
 ###  c4 large_files - List large files
 ###
 ### How to install:
@@ -53,6 +54,10 @@ for opt in $*; do
         nodes=$1
         shift
     elif test "$opt" == "--users"; then
+	shift
+	users=($(echo $1 | sed 's/,/ /g'))
+	shift
+    elif test "$opt" == "--user"; then
 	shift
 	users=($(echo $1 | sed 's/,/ /g'))
 	shift
@@ -109,11 +114,24 @@ elif test $cmd == "head"; then
 	fi
 	if test "${res[@]}" != ""; then printf '%s\n' "${res[@]}"; fi
     done    
+elif test $cmd == "disk_usage"; then
+    if test ${#users[@]} -gt 1 && test "$all" == "FALSE"; then
+	echo "ERROR: Did you forget --me or --user <user>?  If you wish to apply for multiple users, please confirm by specifying --all"
+	exit 1
+    fi
+    for user in ${users[@]}; do
+      echo "$user:"
+      for path in /home/$user/ /data/$user/ /work/$user/; do
+	  if test -d $path; then
+	      du -sh $path
+	  fi
+      done
+      echo
+    done
 elif test $cmd == "large_files"; then
     if test ${#users[@]} -gt 1 && test "$all" == "FALSE"; then
-	echo "ERROR: Did you forget --me?  If you wish to apply for multiple users, please confirm by specifying --all"
+	echo "ERROR: Did you forget --me or --user <user>?  If you wish to apply for multiple users, please confirm by specifying --all"
 	exit 1
-	exit
     fi
     echo "Cluster users: [n=${#users[@]}] ${users[@]}"
 
