ROBUSTNESS: Informative error message if ERROR: cbc --motd is only supported on the head node (cclc01.som.ucsf.edu): n14 is called from compute node [#3]

diff --git a/cbc/shared/bin/cbc b/cbc/shared/bin/cbc
--- a/cbc/shared/bin/cbc
+++ b/cbc/shared/bin/cbc
@@ -21,6 +21,8 @@
 ### Add the following to your ~/.bashrc script:
 ###  source ${SHARED_ROOT}/bashrc
 
+HEAD_NODE="cclc01.som.ucsf.edu"
+
 if test -z "$SHARED_SOFTWARE"; then
   source /home/shared/cbc/bashrc
 fi
@@ -89,7 +91,11 @@ elif test $cmd == "envvars"; then
   echo "** Environment variable set by $SHARED_ROOT/bashrc:"
   grep "^export" $SHARED_ROOT/bashrc | cut -b 8- | cut -d = -f 1 | sort -u
 elif test $cmd == "motd"; then
-  cat /etc/motd
+    if test $HOST != $HEAD_NODE; then
+	echo "ERROR: cbc --motd is only supported on the head node ($HEAD_NODE): $HOST"
+        exit 1
+    fi
+    cat /etc/motd
 fi
 
 
