CLEAUP: source /home/shared/cbc/bashrc is now defunct

diff --git a/cbc/shared/bashrc b/cbc/shared/bashrc
--- a/cbc/shared/bashrc
+++ b/cbc/shared/bashrc
@@ -1,129 +1,17 @@
 #!/usr/bin/env bash
 
-###################################################################
-# Usage:
-# Add the following command to your ~/.bashrc script:
-#   source /home/shared/cbc/bashrc
-#
-# Description:
-# Sets up the PATH to use the most recent versions of software
-# installed by different users.
-#
-# Author: Henrik Bengtsson <henrik.bengtsson@ucsf.edu>
-###################################################################
-
-function is_function() {
-    type $1 &> /dev/null
-    if [[ $? -eq 0 ]]; then echo 1; else echo 0; fi
-}
-
-## '/home/shared/cbc/tipcc/.bashrc' defines several functions used here.
-## It has typically been source before (via /etc/bashrc).  However, in
-## some cases (e.g. cronjobs) this script may be sourced directly. For
-## those cases, we make sure to source the above script here.
-if [[ "$(is_function source_d)" == "0" ]]; then
-    tput setaf 3 2> /dev/null ## yellow
-    >&2 echo "******************************************************************************"
-    >&2 echo "* DEPRECATION WARNING (since 2017-10-28)"
-    >&2 echo "*"
-    >&2 echo "* It looks like you are calling the following:"
-    >&2 echo "*"
-    >&2 echo "*   source /home/shared/cbc/bashrc"
-    >&2 echo "*"
-    >&2 echo "* without first having called:"
-    >&2 echo "*"
-    >&2 echo "*   if [ -f /etc/bashrc ]; then"
-    >&2 echo "*   . /etc/bashrc"
-    >&2 echo "*   fi"
-    >&2 echo "*"
-    >&2 echo "* in your ~/.bashrc."
-    >&2 echo "*"
-    >&2 echo "* This usage will produce an error starting 2017-11-15."
-    >&2 echo "*"
-    >&2 echo "* Regardless, 'source /home/shared/cbc/bashrc' itself is deprecated and"
-    >&2 echo "* will soon become defunct, so please follow our instructions (mentioned"
-    >&2 echo "* elsewhere) on how to use the module framwork instead.";
-    >&2 echo "******************************************************************************"
-    tput sgr0 2> /dev/null    ## reset
-    source /home/shared/cbc/tipcc/.bashrc
-fi
-
-
-
-if [[ "${CBC}" != "false" ]]; then
-    
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Record original state
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-if [[ "${PATH_SYSTEM}" == "" ]]; then
-  export PATH_SYSTEM=${PATH}
-fi
-if [[ "${LD_LIBRARY_PATH_SYSTEM}" == "" ]]; then
-  export LD_LIBRARY_PATH_SYSTEM=${LD_LIBRARY_PATH}
-fi
-
-# Setup SHARED_ROOT
-export SHARED_ROOT=/home/shared/cbc
-source ${SHARED_ROOT}/bin/includes.cbc.bash
-
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Setup PATH depending on system
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-export PATH=${PATH_SYSTEM}
-export LD_LIBRARY_PATH=${LD_LIBRARY_PATH_SYSTEM}
-
-# Added ~/bin/
-if [[ ! -d "${HOME}/bin" ]]; then
-  mkdir ${HOME}/bin
-fi
-appendPath ${HOME}/bin
-
-export HOST=`uname -n`
-export HOST_SHORT=${HOST/.*/}
-export ARCH=`uname -m`
-export ISCOMPUTENODE=0
-if [[ "${HOST_SHORT}" =~ ^n[0-9]{1,2} ]]; then
-  export ISCOMPUTENODE=1
-fi
-
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# SETUP COMPUTE NODES
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-## Set by module cbc-shared (>= 0.1.3)
-export CLUSTER_SCHEDULER="TORQUE"
-export CLUSTER_HEADNODE="cclc01"
-export CLUSTER_NODES="n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 n12 n13 n14 n15 n17 n18 n19 n20 n21 n22 n23 n24 n25 n26 n27 n28 n29 n30"
-
-if [[ "${ISCOMPUTENODE}" = "1" ]]; then
-    prependPath ${SHARED_ROOT}/bin/compute_nodes_only
-fi
-
-
-## FIX: Current users will use CBC Tools
-if [[ ! -f ${HOME}/.cbc ]]; then
-    touch ${HOME}/.cbc
-fi
-
-
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-# Source different .bashrc.d/ paths
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-## CBC Tools?
-export CBC_STARTUP_COMPLETED=
-if [[ -f ${HOME}/.cbc ]]; then
-    source_d "$SHARED_ROOT/.bashrc.d"
-fi
-
-tput setaf 3 2> /dev/null ## yellow
+tput setaf 1 2> /dev/null ## red
 >&2 echo "******************************************************************************"
->&2 echo "* DEPRECATION WARNING (since 2017-10-28)"
+>&2 echo "* DEFUNCT ERROR (since 2017-11-15)"
 >&2 echo "*"
 >&2 echo "* You are using:"
 >&2 echo "*"
 >&2 echo "*   source /home/shared/cbc/bashrc"
 >&2 echo "*"
->&2 echo "* in your startup (e.g. in ~/.bashrc). This will become defunct on 2017-11-15"
->&2 echo "* and then result in an error message. Instead, replace the above with:"
+>&2 echo "* in your startup (e.g. in ~/.bashrc). This is defunct since 2017-11-15."
+>&2 echo "* Calling the above will no longer have an effect, i.e. you are from now on"
+>&2 echo "* only using the default core cluster setup.  To get access to the CBC-shared"
+>&2 echo "* software stack, add"
 >&2 echo "*"
 >&2 echo "*   module load CBC cbc-shared"
 >&2 echo "*"
@@ -133,9 +21,7 @@ tput setaf 3 2> /dev/null ## yellow
 >&2 echo "*   . /etc/bashrc"
 >&2 echo "*   fi"
 >&2 echo "*"
->&2 echo "* and you are good to go. Everything should work the same as before."
+>&2 echo "* (This error message and final reminder will be removed on 2017-11-25)"
 >&2 echo "******************************************************************************"
 tput sgr0 2> /dev/null    ## reset
-
-fi ## if [[ "${CBC}" != "false" ]]
 
